

interface AIResponseProps {
  response: string;
}

const AIResponse = ({ response }: AIResponseProps) => {
  return (
    <div className="ai-response">
      <div className="ai-response-header">
        <h3>💭 AI Reflection</h3>
        <span className="ai-badge">Powered by ChatGPT</span>
      </div>
      
      <div className="ai-response-content">
        {response}
      </div>
      
      <div className="ai-response-footer">
        <p className="ai-disclaimer">
          This reflection is generated by AI to help you think deeper. 
          Your thoughts and experiences are uniquely yours.
        </p>
      </div>
    </div>
  );
};

export default AIResponse; 