import React, { useState } from 'react'
import './App.css'
import { getRandomPrompt } from './services/prompts'

function App() {
  const [currentPrompt, setCurrentPrompt] = useState(getRandomPrompt())
  const [userEntry, setUserEntry] = useState('')
  const [aiResponse, setAiResponse] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const handleNewPrompt = () => {
    setCurrentPrompt(getRandomPrompt())
    setUserEntry('')
    setAiResponse('')
  }

  return (
    <div className="app">
      <header className="app-header">
        <h1>Mental Gym 🧠</h1>
        <p>Daily prompts to strengthen your thinking</p>
      </header>

      <main className="app-main">
        {/* Prompt Card */}
        <div className="prompt-card">
          <div className="prompt-category">
            <span className="category-emoji">
              {currentPrompt.category === 'emotional' ? '💝' : 
               currentPrompt.category === 'creative' ? '🎨' : '🤔'}
            </span>
            <span className="category-label">
              {currentPrompt.category === 'emotional' ? 'Emotional Intelligence' :
               currentPrompt.category === 'creative' ? 'Creative Thinking' : 'Deep Reflection'}
            </span>
          </div>
          
          <div className="prompt-text">
            {currentPrompt.text}
          </div>
          
          <button className="new-prompt-btn" onClick={handleNewPrompt}>
            Try Another Prompt
          </button>
        </div>

        {/* Write Area */}
        <div className="write-area">
          <div className="write-header">
            <h3>Your Thoughts</h3>
            <span className="word-count">
              {userEntry.trim().split(/\s+/).filter(word => word.length > 0).length} words
            </span>
          </div>
          
          <textarea
            value={userEntry}
            onChange={(e) => setUserEntry(e.target.value)}
            placeholder="Start writing your thoughts here... Take your time and be honest with yourself."
            className="write-textarea"
            rows={8}
          />
          
          <div className="write-actions">
            <button 
              onClick={async () => {
                if (!userEntry.trim()) {
                  alert('Please write something first!');
                  return;
                }

                setIsLoading(true);
                
                try {
                  const { getAIReflection } = await import('./services/claude');
                  const response = await getAIReflection(userEntry, currentPrompt.text);
                  setAiResponse(response);
                } catch (error) {
                  console.error('Error getting AI feedback:', error);
                  setAiResponse("Thanks for sharing your thoughts! I'm having trouble connecting right now, but your reflection is valuable.");
                } finally {
                  setIsLoading(false);
                }
              }}
              disabled={isLoading || !userEntry.trim()}
              className="ai-feedback-btn"
            >
              {isLoading ? 'Getting thoughtful feedback...' : 'Get AI Reflection'}
            </button>
            
            {userEntry.length > 20 && !aiResponse && (
              <p className="ai-hint">
                ✨ Ready for some thoughtful feedback? Click above when you're done writing.
              </p>
            )}
          </div>
        </div>

        {/* AI Response */}
        {aiResponse && (
          <div className="ai-response">
            <div className="ai-response-header">
              <h3>💭 AI Reflection</h3>
              <span className="ai-badge">Powered by ChatGPT</span>
            </div>
            
            <div className="ai-response-content">
              {aiResponse}
            </div>
            
            <div className="ai-response-footer">
              <p className="ai-disclaimer">
                This reflection is generated by AI to help you think deeper. 
                Your thoughts and experiences are uniquely yours.
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

export default App
